spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.0.131:3306/goldencis_osa?generateSimpleParameterMetadata=true&amp;characterEncoding=UTF-8
    username: root
    password: goldencis
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: detect
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterAccess=600s
  redis:
    database: 0
    host: 10.10.0.131
    port: 38019
    timeout: 10000
    jedis:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 10000

server:
  port: 80
  servlet:
    context-path: /osa

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

guava:
  cacheSize: 10000
  timeLength: 1000
